### PR TITLE
Remove dead code.

### PR DESCRIPTION
**Pull request by patzim**

### CODE REVIEW

**Comment by lizmat** [comment]
Hmmm... how can you be sure that that is dead code?

**Comment by jnthn** [comment]
@lizmat Looks like `$prefix` is never used after this point.

**Comment by lizmat** [comment]
Perhaps then `$prefix` should be reduced to `$` in the signature as well ?

**Comment by zoffixznet** [comment]
Doesn't line 13 has a typo and instead of assigning to `$prefix` it should be assigning to `$realpath`?

**Comment by patzim** [comment]
This got stale. I'll have a broader look at this code in general soonish. So close this.

**Pull request closed without merging**
