### PR TITLE
[JVM] Fix eof detection after read from empty file

### PR DESCRIPTION
**Pull request by usev6**

### CODE REVIEW

**Comment by usev6** [comment]
I didn't look at the decoder stuff before, so I would appreciate a short review.

**Comment by tbrowder** [comment]
I can’t comment on the PR except to say it *may* cure an existing subtle problem with stderr and spawnprocasync on the jvm. I would like to see it merged soon.

**Comment by usev6** [comment]
Well, I went ahead and merged the PR myself.

**Comment by tbrowder** [comment]
Thanks!

**Pull request merged**
