### PR TITLE
add new test file for nqp using perl

### PR DESCRIPTION
**Pull request by tbrowder**
+ provides a test harness for testing known failures
+ test for known failure using =cut

### CODE REVIEW

**Comment by zoffixznet** [comment]
`xt/` is generally for author tests while `t/` is for user tests. This PR seems to be adding POD tests as author tests (is that necessary?) while at the same time it's adding author tests to be run with `make test`, along side user tests.

**Comment by tbrowder** [comment]
The test should be standard, but they use perl 5 so they need to be in a separate dir from the “exec nqp” tests.  I forgot the special convention for xt, how about some other, unique dir then like “t/perl5/<lang>”?

**Comment by zoffixznet** [comment]
Personally, I'd just write the nqp version of STDERR capturing routine instead of writing an entire test file in Perl 5 just to execute a program that creates a file.

JS back end even [already has an implementation that can be adapted](https://github.com/perl6/nqp/blob/b88de49aadefc1fe758197d51a71cc8173064dbf/src/vm/js/HLL/Backend.nqp#L4-L69)

**Comment by tbrowder** [comment]
I’ll close this and resubmit after we decide where to put the Perl 5 tests for <lang>.

**Pull request closed without merging**
