### PR TITLE
Expose 'slice' op in NQP (MoarVM / JVM/ JS)

### PR DESCRIPTION
**Pull request by jstuder-gh**
Exposes a lower-level means of taking positional slices.

    slice(@arr, int $start_elem, int $end_elem --> @copy)

Requires this [MoarVM PR](https://github.com/MoarVM/MoarVM/pull/843)

### CODE REVIEW

**Comment by jstuder-gh** [comment]
Added additional commits. In addition to exposing the MoarVM slice op, also added commits to port slice to the P6 runtime for the JVM backend.

Changed the name of the PR to indicate these additions.

**Comment by lizmat** [comment]
I'm not sure I like the semantics of negative indices.  In things like `atpos`, a negative index means substracted from `nqp::elems`, so `-2` would be the same as `nqp::elems - 2`

$ 6 'use nqp; my $l := nqp::list(1,2,3); say nqp::atpos($l, -2)'
2

It would seem to me that the same semantics would be expected / useful for the `slice` op.

And apologies for not digging into this sooner.  I *really* like that you're doing this!

**Comment by jstuder-gh** [comment]
You're right, that would be better. Not only is it more consistent but it also provides more flexibility. I'll modify it to address this issue.

**Comment by lizmat** [comment]
@jstuder-gh looks ok to me, except for the Travis problem: do you have any idea what's going on there?

**Comment by ugexe** [comment]
It would need the appropriate MoarVM PR merged to work

**Comment by jstuder-gh** [comment]
Yeah its kind of weird when a project is split up over several repos. I guess if we had MoarVM as a submodule it could work.

**Pull request merged**
