### PR TITLE
Pass --execname to nqp thus nqp::execname() works

### PR DESCRIPTION
**Pull request by W4anD0eR96**

### CODE REVIEW

**Comment by W4anD0eR96** [comment]
I'm only test on Mac OS X with MoarVM backend. So make it a pull request to prevent any mistake.

**Comment by W4anD0eR96** [comment]
still I don't know how to pass `execname` variable in JS backend @pmurias

**Comment by ugexe** [comment]
It would be wise to build a rakudo against this and run the roast on it.

**Comment by W4anD0eR96** [comment]
Tested with rakudo/t/* and several roast(I want a `./fudgeandtestall` though), all looks ok with MoarVM backend. It seems JVM backend of Perl 6 impls `execname` by a more different way..

**Comment by W4anD0eR96** [comment]
Only enable `nqp::execname()` on MoarVM backend, I have no idea how to impl it clean in JVM, but I think this is a net win, thus merge this once CI pass. And as mentioned above, it would not break rakudo build and roast test

**Pull request merged**
