### PR TITLE
Fix 'Substr length cannot be negative' from Match

### PR DESCRIPTION
**Pull request by ugexe**
I don't understand why this should change anything, but it does.

Fixes Grammar::HTTP - see:
https://github.com/ugexe/Perl6-Grammar--HTTP/issues/6
https://irclog.perlgeek.de/perl6-dev/2017-05-02#i_14521237

### CODE REVIEW

**Comment by ugexe** [comment]
Note the difference (current master):
```
$ perl6 -e 'grammar Foo { token TOP { <tox> }; token tox { .+ }; }; say Foo.parse("xyz")'
｢xyz｣
 tox => ｢xyz｣

$ perl6 -e 'grammar Foo { token TOP { <to> }; token to { .+ }; }; say Foo.parse("xyz")'
｢｣
 to => ｢｣
```

This PR fixes the second case.

**Comment by lizmat** [comment]
Wouldn't just replacing `self.do` with `$!do` also fix the issue?

**Comment by ugexe** [comment]
@lizmat Doing so results in `Substring length (-358) cannot be negative` during stage2

**Comment by lizmat** [comment]
Ok, that would imply that the `to` method is not a simple accessor.  Maybe there's more logic in there that you would need to emulate.

**Comment by ugexe** [comment]
That just shows the `to` method logic (which is inlined in this PR) is needed for cases when `$!to` is negative. In the golfed grammar example the `token to {  }` changes the behavior of `NQPMatchRole.to` internally. Yet if we change 2 instances of `self.to` to `$!to < 0 ?? $!pos !! $!to` (the inlined code of `self.to`), as seen in the PR, the `token to { }` no longer affects the internals.

**Comment by W4anD0eR96** [comment]
@ugexe is this problem fix other place?

**Pull request closed without merging**
