### PR TITLE
add a new built-in sub: run-command

### PR DESCRIPTION
**Pull request by tbrowder**
+ add tests for the run-command
+ add test for improved pod-panic msg
  using the new sub run-command

### CODE REVIEW

**Comment by niner** [comment]
What's the purpose of this new sub?
Shouldn't it be part of the 6.d setting? At least for subs we can easily stay 100 % backwards compatible and we should use that advantage.

**Comment by niner** [comment]
Ah, sorry, shouldn't have commented before finishing my coffee. Didn't notice that this is the nqp repo.

**Comment by AlexDaniel** [comment]
But even if so, to me it feels like this should be a helper sub for tests only. But maybe I'm missing something.

**Comment by zoffixznet** [comment]
FWIW, there's a [`src/core/testing.nqp` file](https://github.com/perl6/nqp/blob/master/src/core/testing.nqp] for testing routines, though it'd be available in the setting just the same as `is` or `ok` are.

> this should be a helper sub for tests only. But maybe I'm missing something.

I think there's a limitation that NQP modules must be already precompiled, so you have a choice of shoving this helper routine into the setting, repeating it in each test file, or figuring out how to precompile a helper test module.

**Comment by tbrowder** [comment]
I need to be able to test various pod failures in nqp on my road to a slang for pod in nqp and then Perl 6. I do not want to copy/paste so much boiler plate every time I need a new test.

**Comment by tbrowder** [comment]
failing on travis, closing and will reopen after fixing

**Pull request closed without merging**
