### PR TITLE
More robust test

### PR DESCRIPTION
**Pull request by W4anD0eR96**

### CODE REVIEW

**Comment by W4anD0eR96** [comment]
@tbrowder I wonder if this is your intention. If we have `./nqp`, then `./nqp` is the right command, isn't it?

**Comment by W4anD0eR96** [comment]
or we can make sure that there is ONLY `./nqp`

**Comment by ugexe** [comment]
The original code seems more correct -- consider if both jvm and moarvm backends are installed.

**Comment by W4anD0eR96** [comment]
@ugexe see #467, there is a situation that only `./nqp` exist.

Could it be
```
my $cmd;
if ((nqp::stat('./nqp-m', nqp::const::STAT_EXISTS) == 0)
    && (nqp::stat('./nqp-j', nqp::const::STAT_EXISTS) == 0)) {
    $cmd := './nqp';
} else {
    $cmd := nqp::getcomp('nqp').backend.name eq 'jvm' ?? './nqp-j' !! './nqp-m';
}
```
or just, at co #477 , throw if `./nqp*` doesn't exist.

**Comment by ugexe** [comment]
Your new code seems reasonable to me.

Maybe https://github.com/perl6/nqp/blob/master/docs/ops.markdown#execname could provide a more robust solution/general solution in the future.

**Comment by W4anD0eR96** [comment]
You're right. It seems what should be improved is `tools/build/gen-xxx-runner.pl`

**Comment by W4anD0eR96** [comment]
close for #479

**Comment by W4anD0eR96** [comment]
MoarVM backend could easily introduce `execname` but JVM backend introduces it (in rakudo) somewhat weird, thus reopen this PR and temporarily to avoid user-block case in #467

**Pull request merged**
