### PR TITLE
add a test for stderr in spawnprocasync

### PR DESCRIPTION
**Pull request by tbrowder**
+ provides a partial fix for nqp GH #409 (no test for merge yet)
+ adds comments for the test
+ organizes code to be more readable

### CODE REVIEW

**Comment by tbrowder** [comment]
I need this merged before I resubmit the run-command PR (which will move the sub to testing.nqp) and rearrange the several tests using spawnprocasynch in a better dependency order.

**Comment by AlexDaniel** [comment]
This failed on JVM, why?

**Comment by tbrowder** [comment]
I’m investigating, but know nothing about the jvm.

**Comment by tbrowder** [comment]
will close and resubmit after the jvm failure is taken care of

**Pull request closed without merging**
